---
# The following workaround is required if VirtualBox Shared Folders are being used on Windows.
# Without it the Flow Manager configuration file cannot be updated in place with Ansible's
# 'replace' module. A "[Errno 26] Text file busy" error will be returned.

- block:

    - name: Copy Flow Manager configuration file to temporary location in a Vagrant environment
      command: cp "{{ nodejs_app_install_dir }}/gpii/configs/gpii.config.cloudBased.flowManager.production.json" /tmp/gpii.config.cloudBased.flowManager.production.json

    - name: Update the Flow Manager configuration file's Preference Server address
      replace:
        dest: /tmp/gpii.config.cloudBased.flowManager.production.json
        regexp: 'http://preferences.gpii.net/preferences'
        replace: 'http://{{ flow_manager_preferences_server_host_address }}/preferences'
      notify: Restart the application systemd unit

    - name: Move Flow Manager configuration file back to original location in a Vagrant environment
      command: mv /tmp/gpii.config.cloudBased.flowManager.production.json "{{ nodejs_app_install_dir }}/gpii/configs/gpii.config.cloudBased.flowManager.production.json"

  when: is_vagrant

# If VirtualBox Shared Folders on Windows aren't being used then modify files directly.
- name: Update the Flow Manager configuration file's Preference Server address
  replace:
    dest: "{{ nodejs_app_install_dir }}/gpii/configs/gpii.config.cloudBased.flowManager.production.json"
    regexp: 'http://preferences.gpii.net/preferences'
    replace: 'http://{{ flow_manager_preferences_server_host_address }}/preferences'
  notify: Restart the application systemd unit
