---
# The following workaround is required if VirtualBox Shared Folders are being used on Windows.
# Without it the Flow Manager configuration file cannot be updated in place with Ansible's
# 'replace' module. A "[Errno 26] Text file busy" error will be returned.

- block:

    - name: Copy Flow Manager configuration file to temporary location in a Vagrant environment
      command: cp '{{ nodejs_app_install_dir }}/{{ item.path }}/{{ item.file }}' '/tmp/{{ item.file }}'
      with_items:
        - { path: 'gpii/configs', file: 'gpii.config.cloudBased.flowManager.production.json' }
        - { path: 'gpii/configs', file: 'gpii.config.cloudBased.production.json' }
        - { path: 'gpii/node_modules/flowManager/configs', file: 'gpii.flowManager.config.production.json' }

    - name: Replace the production Preferences Server's address with a user provided one
      replace:
        dest: '/tmp/{{ item }}'
        regexp: 'preferences.gpii.net'
        replace: '{{ flow_manager_preferences_server_host_address }}'
      notify: Restart the application systemd unit
      with_items:
        - gpii.config.cloudBased.flowManager.production.json
        - gpii.config.cloudBased.production.json
        - gpii.flowManager.config.production.json

    - name: Move Flow Manager configuration file back to original location in a Vagrant environment
      command: mv '/tmp/{{ item.file }}' '{{ nodejs_app_install_dir }}/{{ item.path }}/{{ item.file }}'
      with_items:
        - { path: 'gpii/configs', file: 'gpii.config.cloudBased.flowManager.production.json' }
        - { path: 'gpii/configs', file: 'gpii.config.cloudBased.production.json' }
        - { path: 'gpii/node_modules/flowManager/configs', file: 'gpii.flowManager.config.production.json' }

  when: is_vagrant

# If VirtualBox Shared Folders on Windows aren't being used then modify files directly.
- name: Replace the production Preferences Server's address with a user provided one
  replace:
    dest: '{{ nodejs_app_install_dir }}/{{ item.path }}/{{ item.file }}'
    regexp: 'preferences.gpii.net'
    replace: '{{ flow_manager_preferences_server_host_address }}'
  notify: Restart the application systemd unit
  with_items:
    - { path: 'gpii/configs', file: 'gpii.config.cloudBased.flowManager.production.json' }
    - { path: 'gpii/configs', file: 'gpii.config.cloudBased.production.json' }
    - { path: 'gpii/node_modules/flowManager/configs', file: 'gpii.flowManager.config.production.json' }
